---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
    register: result

  - name: Delete instances
    os_server:
      cloud: openstack
      state: absent
      server: "{{ item.name}}"
    loop: "{{ result.openstack_servers }}"