- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{ lookup('env', 'OSP_GUID') }}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  gather_facts: true
  roles:
   - osp-servers