---

# tasks file for osp.servers
- debug:
    var: item
  loop: "{{ osp_servers | dict2items | json_query('[].value') }}"

- name: Create Instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: present
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_group }}"
    delete_fip: yes
    wait: no
    meta: "{{ item.meta }}"
    userdata: |
      #!/bin/bash
      echo "{{ openstack_key }}" >> /home/cloud-user/.ssh/authorized_keys
      echo "{{ dev_key }}" >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ osp_servers | dict2items | json_query('[].value') }}"
