- name: Create Inventory
  tower_inventory:
    name: "{{ ec2_dynamic_inventory }}"
    organization: "{{ org_name }}"
    state: present


- name: Create groups needed to deploy app
  tower_group:
    name: "{{ item }}"
    inventory: "{{ ec2_dynamic_inventory }}"
    state: present
  loop:
    - apps 
    - appdbs
    - frontends
    - bastions
    - tag_AnsibleGroup_bastions
    - tag_AnsibleGroup_frontends
    - tag_AnsibleGroup_apps
    - tag_AnsibleGroup_appdbs

- name: Associate AWS tags to parent
  tower_group:
    name: "{{ item }}"
    children: 
      - "tag_AnsibleGroup_{{ item }}"
    inventory: "{{ ec2_dynamic_inventory }}"
  loop:
    - bastions
    - frontends
    - apps
    - appdbs

- name: Add localhost as host 
  tower_host:
    name: localhost
    inventory: "{{ ec2_dynamic_inventory }}"
    variables: "@/root/inventory_vars.json"

- name: Create inventory source with ec2 script
  tower_inventory_source:
    name: "{{ec2_inventory_source}}"
    inventory: "{{ec2_dynamic_inventory}}"
    source: ec2
    credential: "{{aws_read_keys}}"
    source_regions: "{{aws_region_name}}"
    instance_filters: "{{ tag_filters }}"
    overwrite: true
    update_on_launch: true