- name: Machine Credential to connect to git repo
  tower_credential:
    name: homework_repo
    organization: "{{ org_name }}"
    state: present
    kind: scm
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ lookup('file', '/root/.ssh/5bc4key.pem') }}"
    username: opentlc-mgrs

- name: Create Homework Assignment project
  tower_project:
    name: "{{ proj_name }}"
    description: "Ansible Boot Camp Homework"
    organization: "{{ org_name }}"
    scm_url: "{{ scm_url }}"
    scm_type: git
    scm_credential: homework_repo
    scm_branch: "{{ scm_branch }}"
    scm_update_on_launch: true
    state: present

- name: Machine Credential to connect to workstation using openstack.pub
  tower_credential:
    name: "{{ ssh_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{ tower_GUID }}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    ssh_key_data: "{{ lookup('file', user_cred_path) }}"
    username: "{{ user_cred_name }}"

- name: Create Inventory
  tower_inventory:
    name: "{{static_inventory_name}}"
    organization: "{{org_name}}"
    state: present
    tower_config_file: "{{ tower_cfg }}"

- name: Create Group in static inventory 
  tower_inventory:
    name: "{{group_name}}"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_config_file: "{{ tower_cfg }}"

- name: Add tower host
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data: "{{ lookup('file', opentlc_cred_path) }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

